# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Travel Blog CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      NEXT_CONTENTFUL_SPACE_ID: ${{ secrets.NEXT_CONTENTFUL_SPACE_ID }}
      NEXT_CONTENTFUL_ACCESS_TOKEN: ${{ secrets.NEXT_CONTENTFUL_ACCESS_TOKEN }}
      GOOGLE_MAP_API_KEY: ${{ secrets.GOOGLE_MAP_API_KEY }}
        
    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: next install & build
      run: | 
        npm install --save --legacy-peer-deps
        npx next build
       
